-- MySQL Script generated by MySQL Workbench
-- 08/05/15 22:22:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`clientes` (
  `Id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `rfc` VARCHAR(13) NULL,
  `numero` VARCHAR(10) NULL,
  `estado` VARCHAR(45) NULL,
  `direccion` VARCHAR(50) NULL,
  `colonia` VARCHAR(45) NULL,
  `noExt` INT NULL,
  `ccp` INT NULL,
  PRIMARY KEY (`Id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`provedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`provedores` (
  `Id_provedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `numero` VARCHAR(10) NULL,
  `rfc` VARCHAR(13) NULL,
  `correo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `colonia` VARCHAR(45) NULL,
  `noExt` INT NULL,
  `ccp` INT NULL,
  `fechaEntrega` DATE NULL,
  PRIMARY KEY (`Id_provedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`productos` (
  `Id_producto` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `tipo` ENUM('Alimento', 'Bebida', 'Golosina') NULL,
  `precio` FLOAT NULL,
  `costo` FLOAT NULL,
  `elaboracion` ENUM('Interno', 'Externo') NULL,
  `cantidad` VARCHAR(45) NULL,
  `stock` INT NULL,
  `Id_provedor` INT NULL,
  PRIMARY KEY (`Id_producto`),
  INDEX `fk_productos_provedores_idx` (`Id_provedor` ASC),
  CONSTRAINT `fk_productos_provedores`
    FOREIGN KEY (`Id_provedor`)
    REFERENCES `inventario`.`provedores` (`Id_provedor`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`ingresoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`ingresoProducto` (
  `Id_ingresoProducto` INT NOT NULL AUTO_INCREMENT,
  `productoAnterior` INT NULL,
  `productoIngresado` INT NULL,
  `productoNuevo` INT NULL,
  `fechaIngreso` VARCHAR(20) NULL,
  `Id_producto` INT NULL,
  `nameUsername` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_ingresoProducto`),
  INDEX `fk_ingresoProducto_productos1_idx` (`Id_producto` ASC),
  CONSTRAINT `fk_ingresoProducto_productos1`
    FOREIGN KEY (`Id_producto`)
    REFERENCES `inventario`.`productos` (`Id_producto`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`cortes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`cortes` (
  `Id_corte` INT NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(100) NULL,
  `datos` BLOB(100) NULL,
  `fechaCorte` VARCHAR(20) NULL,
  `costoElaboracion` VARCHAR(45) NULL,
  `totalVendido` VARCHAR(45) NULL,
  `ganancia` VARCHAR(45) NULL,
  `nameUsername` VARCHAR(45) NULL,
  `datosHtml` BLOB(100) NULL,
  PRIMARY KEY (`Id_corte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`vendidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`vendidos` (
  `Id_vendidos` INT NOT NULL AUTO_INCREMENT,
  `totalVendidos` FLOAT NULL,
  `cantidadVendidos` INT NULL,
  `Id_producto` INT NULL,
  PRIMARY KEY (`Id_vendidos`),
  INDEX `fk_vendidos_productos1_idx` (`Id_producto` ASC),
  CONSTRAINT `fk_vendidos_productos1`
    FOREIGN KEY (`Id_producto`)
    REFERENCES `inventario`.`productos` (`Id_producto`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
