-- MySQL Script generated by MySQL Workbench
-- 08/05/15 22:43:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema login
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema login
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `login` DEFAULT CHARACTER SET latin1 ;
USE `login` ;

-- -----------------------------------------------------
-- Table `login`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`areas` (
  `Id_area` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_area` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_area`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `login`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`empleados` (
  `Id_empleado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `colonia` VARCHAR(45) NULL DEFAULT NULL,
  `noExt` INT(11) NULL DEFAULT NULL,
  `ccp` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_empleado`),
  UNIQUE INDEX `correo` (`correo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `login`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`usuarios` (
  `Id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `Id_area` INT(11) NULL,
  `Id_empleado` INT(11) NULL,
  `fechaAlta` VARCHAR(45) NULL,
  `estatus` TINYINT(1) NULL,
  PRIMARY KEY (`Id_usuario`),
  UNIQUE INDEX `username` (`username` ASC),
  INDEX `fk_usuarios_areas_idx` (`Id_area` ASC),
  INDEX `fk_usuarios_empleados1_idx` (`Id_empleado` ASC),
  FULLTEXT INDEX `password` (`password` ASC),
  CONSTRAINT `fk_usuarios_areas`
    FOREIGN KEY (`Id_area`)
    REFERENCES `login`.`areas` (`Id_area`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_usuarios_empleados1`
    FOREIGN KEY (`Id_empleado`)
    REFERENCES `login`.`empleados` (`Id_empleado`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `login`.`salt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`salt` (
  `Id_salt` INT NOT NULL AUTO_INCREMENT,
  `Id_usuario` INT(11) NOT NULL,
  `saltAltaUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_salt`),
  INDEX `fk_salt_usuarios1_idx` (`Id_usuario` ASC),
  CONSTRAINT `fk_salt_usuarios1`
    FOREIGN KEY (`Id_usuario`)
    REFERENCES `login`.`usuarios` (`Id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
